feat: added responsive to fit TV (16:9 aspect ratio)
BPR-Data-Team/Election-Night pull request #104
Opened 2024-09-30 05:17 UTC by johnlhuangP

I was under the assumption that the TV will have a 16:9 aspect ratio, but please correct me if I am mistaken. I adjusted the sizing of the buttons to fit as the screen enlarges. I did not account for smaller screens.

2024-09-30 18:08 UTC, arielshif requested changes

2024-09-30 18:08 UTC, arielshif commented on election-portal/app/assets/finance.svg
You should check out the discussion under Louis' merge. Icons can get implemented as react-icons. Their size can be adjusted through font-size, which will allow conformity to manual browser scaling.

https://github.com/BPR-Data-Team/Election-Night/pull/97#discussion_r1777620976

2024-09-30 18:08 UTC, arielshif commented on election-portal/app/page.tsx
can be easily switched out to react icons. lmk if you want exact code or check out https://github.com/BPR-Data-Team/ElectionModel2024-site/blob/69301156e65214e5a8dc00e489db8168ec71ffa2/src/components/Footer.tsx for an example in prod

2024-09-30 18:08 UTC, arielshif commented
code looks good! just left a few comments about how we're implementing icons for consistency

2024-10-01 17:09 UTC, johnlhuangP commented
Thanks for the comments. I will fix those up.

2024-10-01 18:01 UTC, johnlhuangP commented
Hi, just changed to react-icons. I am a little unsure about the icon for Election breakdown because I did not find an icon on react-icons that looked like the one on the figma.

2024-10-01 21:46 UTC, arielshif approved these changes
approved but will let @akslaym merge

2024-10-02 03:57 UTC, akslaym approved these changes

2024-10-02 03:57 UTC, akslaym commented
I had this working on a big TV screen which is great.

2024-10-02 03:57 UTC, merged